import { prisma } from "@/lib/db";

/**
 * Rekap absensi (PRD §16).
 * Dipakai bersama oleh halaman `/laporan` dan export CSV, supaya angka di
 * layar dan angka di file CSV dijamin sama sumbernya.
 */

export const STATUS_LABEL: Record<string, string> = {
  PRESENT: "Hadir",
  LATE: "Terlambat",
  EARLY_LEAVE: "Pulang Awal",
  ABSENT: "Alpa",
  LEAVE: "Cuti",
  SICK: "Sakit",
  HOLIDAY: "Libur",
  DAY_OFF: "Hari Libur",
  OVERTIME: "Lembur",
  INCOMPLETE: "Belum Lengkap",
  REJECTED: "Ditolak",
};

export type FilterLaporan = {
  dari: string;
  sampai: string;
  departemen?: string;
  employeeId?: string;
  status?: string;
};

/**
 * Rentang inklusif. Kolom `attendance.date` adalah `@db.Date`, jadi batasnya
 * pukul 00:00 UTC — bukan `setHours` lokal yang di UTC+7 mundur sehari.
 */
export function rentangTanggal(dari: string, sampai: string) {
  return {
    gte: new Date(dari + "T00:00:00.000Z"),
    lte: new Date(sampai + "T00:00:00.000Z"),
  };
}

export function whereAbsensi(f: FilterLaporan) {
  const employee: Record<string, unknown> = {};
  if (f.departemen) employee.departmentId = f.departemen;
  if (f.employeeId) employee.id = f.employeeId;

  const where: Record<string, unknown> = { date: rentangTanggal(f.dari, f.sampai) };
  if (Object.keys(employee).length) where.employee = employee;
  if (f.status) where.status = f.status;
  return where;
}

export type BarisLaporan = {
  id: string;
  tanggal: string;
  employeeCode: string;
  fullName: string;
  departemen: string;
  shift: string;
  checkIn: string | null;
  checkOut: string | null;
  status: string;
  lateMinutes: number;
  workMinutes: number;
  overtimeMinutes: number;
  distanceFromOffice: number | null;
  rejectionReason: string | null;
  adaFoto: boolean;
};

const jam = (d: Date | null) => (d ? d.toTimeString().slice(0, 5) : null);

export async function ambilLaporan(f: FilterLaporan): Promise<BarisLaporan[]> {
  const absensi = await prisma.attendance.findMany({
    where: whereAbsensi(f),
    orderBy: [{ date: "desc" }, { employee: { fullName: "asc" } }],
    include: {
      employee: { select: { employeeCode: true, fullName: true, department: { select: { name: true } } } },
      shift: { select: { name: true } },
    },
  });

  return absensi.map((a) => ({
    id: a.id,
    tanggal: a.date.toISOString().slice(0, 10),
    employeeCode: a.employee.employeeCode,
    fullName: a.employee.fullName,
    departemen: a.employee.department?.name ?? "-",
    shift: a.shift?.name ?? "-",
    checkIn: jam(a.checkIn),
    checkOut: jam(a.checkOut),
    status: a.status,
    lateMinutes: a.lateMinutes,
    workMinutes: a.workMinutes,
    overtimeMinutes: a.overtimeMinutes,
    distanceFromOffice: a.distanceFromOffice,
    rejectionReason: a.rejectionReason,
    // Kolom `photo` berisi dataURL base64, bisa ratusan KB. Jangan pernah
    // ikut serialisasi ke laporan — cukup penanda ada/tidak.
    adaFoto: Boolean(a.photo),
  }));
}

export type Ringkasan = {
  total: number;
  hadir: number;
  terlambat: number;
  alpa: number;
  terlambatMenit: number;
  lemburMenit: number;
  jamKerja: number;
};

export function ringkas(baris: BarisLaporan[]): Ringkasan {
  const r: Ringkasan = { total: baris.length, hadir: 0, terlambat: 0, alpa: 0, terlambatMenit: 0, lemburMenit: 0, jamKerja: 0 };
  for (const b of baris) {
    if (b.status === "PRESENT" || b.status === "OVERTIME" || b.status === "EARLY_LEAVE") r.hadir++;
    if (b.status === "LATE") { r.hadir++; r.terlambat++; }
    if (b.status === "ABSENT") r.alpa++;
    r.terlambatMenit += b.lateMinutes;
    r.lemburMenit += b.overtimeMinutes;
    r.jamKerja += b.workMinutes;
  }
  return r;
}

/** Selektor RFC 4180: bungkus nilai yang punya koma/kutip/baris baru. */
function sel(value: string | number | null): string {
  const s = value === null ? "" : String(value);
  return /[",\n\r]/.test(s) ? '"' + s.replace(/"/g, '""') + '"' : s;
}

export function keCsv(baris: BarisLaporan[], ringkasan: Ringkasan, f: FilterLaporan, dibuatOleh: string): string {
  const kepala = [
    "Kode", "Nama", "Departemen", "Shift", "Tanggal", "Check In", "Check Out", "Status",
    "Terlambat (menit)", "Jam Kerja (menit)", "Lembur (menit)", "Jarak (m)", "Foto", "Alasan Ditolak",
  ];

  const isi = baris.map((b) =>
    [
      b.employeeCode, b.fullName, b.departemen, b.shift, b.tanggal, b.checkIn, b.checkOut,
      STATUS_LABEL[b.status] ?? b.status, b.lateMinutes, b.workMinutes, b.overtimeMinutes,
      b.distanceFromOffice === null ? "" : Math.round(b.distanceFromOffice), b.adaFoto ? "ya" : "tidak",
      b.rejectionReason,
    ].map(sel).join(","),
  );

  // PRD §16: report mencatat Generated By, Generated At, Period, dan Filter.
  const meta = [
    ["Laporan", "Rekap Absensi"],
    ["Dibuat oleh", dibuatOleh],
    ["Dibuat pada", new Date().toISOString()],
    ["Periode", `${f.dari} s/d ${f.sampai}`],
    ["Filter departemen", f.departemen ? f.departemen : "semua"],
    ["Filter karyawan", f.employeeId ? f.employeeId : "semua"],
    ["Filter status", f.status ? STATUS_LABEL[f.status] ?? f.status : "semua"],
    [],
    ["Ringkasan", ""],
    ["Total catatan", ringkasan.total],
    ["Hadir", ringkasan.hadir],
    ["Terlambat", ringkasan.terlambat],
    ["Alpa", ringkasan.alpa],
    ["Total keterlambatan (menit)", ringkasan.terlambatMenit],
    ["Total lembur (menit)", ringkasan.lemburMenit],
    ["Total jam kerja (menit)", ringkasan.jamKerja],
  ].map((r) => r.map(sel).join(",")).join("\r\n");

  // BOM supaya Excel di Windows tidak salah baca UTF-8. Ditulis sebagai
  // escape, bukan karakter literal — karakter literal bisa hilang saat file
  // dibuka di editor dengan encoding lain.
  return "\uFEFF" + meta + "\r\n\r\n" + kepala.map(sel).join(",") + "\r\n" + isi.join("\r\n") + "\r\n";
}
